### ISSUE TITLE
Will the training code for diffuse and specular networks be released?

### ISSUE THREAD

**Issue by GH-HOME** [nexuslrf/ENVIDR#2]
Dear authors,

Thanks a lot for releasing the implementation of this tremendous work. I wonder whether the training code for the diffuse and specular network will be released?

Best
Heng

**Comment by nexuslrf** [comment]
Thanks for your interest. Unfortunately I am recently on vacation and also in bad health (maybe Covid 🤒️). I’ll start working on releasing full codebase next week. If everything works well, code will be available within two weeks.
