### ISSUE TITLE
How should I get ngp.pth?

### ISSUE THREAD

**Issue by jpsml** [nexuslrf/ENVIDR#8]
I'm getting an error when I try to run the following experiment:

python main_nerf.py --config ./configs/scenes/materials.ini

The error is the following:

FileNotFoundError: [Errno 2] No such file or directory: 'exps/envs_all_11_unit_en_renv/checkpoints/ngp.pth'

Please, would you tell me what I should do in order to obtain this ngp.pth file?

**Comment by jpsml** [comment]
Please, would you be able to provide the pretrained "exps/envs_all_11_unit_en_renv/checkpoints/ngp.pth" model? Or is there any way to proceed with the experiment without it?

**Comment by nexuslrf** [comment]
Hi, 

Sorry for your inconvenience! You can use this [`rendering_mlps.pth`](https://github.com/nexuslrf/ENVIDR/blob/main/ckpts/rendering_mlps.pth) to replace that missing `ngp.pth` they are the same checkpoint.

Best
